### ISSUE TITLE
error loading the example model

### ISSUE THREAD

**Issue by Eytanm** [BladeTransformerLLC/gauzilla#5]
Hello,
Built the project successfully, and when loading an example model (your models),
getting an error:

gauzilla.js:344 panicked at src\scene.rs:106:91:
called `Result::unwrap()` on an `Err` value: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (http://localhost:8080/pkg/gauzilla.js:328:21)

Please advise

![gau1_2](https://github.com/BladeTransformerLLC/gauzilla/assets/29125970/a2b1c712-3e79-4e44-9f91-b5c4a1990056)
![gau1](https://github.com/BladeTransformerLLC/gauzilla/assets/29125970/c2cecd71-afed-453d-bd09-37908677f8f0)

**Comment by BladeTransformerLLC** [comment]
Which model are you trying to load? The PLY file format differs slightly depending on 3DGS training apps (eg. Scaniverse omits normals entirely).

**Comment by Eytanm** [comment]
This is an error produced when trying to load any of the example **models provided by the Guazilla library.**

**Comment by BladeTransformerLLC** [comment]
There is no such file `input.ply` in the Gauzilla datasets.
